### ISSUE TITLE
TAP

### ISSUE THREAD

**Issue by myller-silva** [myller-silva/gp-armarios-ifce#1]
## Objetivo:
Elaborar o Termo de Abertura do Projeto (TAP) para o Sistema de Gerenciamento de Armários do IFCE, definindo o escopo, stakeholders, cronograma e recursos necessários para o desenvolvimento do projeto.

## Tarefas a serem realizadas:

- [x] Completar o preenchimento do TAP com as informações relevantes. 
- [x] Disponibilizar o link para o TAP no repositório do projeto.

## Critérios de Aceitação:

- [x] TAP finalizado e documentado de forma clara e organizada.
- [x] Link do TAP adicionado ao repositório do projeto para fácil acesso.
- [x] Aprovação do TAP por todos os stakeholders relevantes.

**Comment by myller-silva** [comment]
link para o [TAP](https://docs.google.com/document/d/1muwwBUx5FUEhYwQdxrG4zqsdmygp13eMOvODldx0Yb8/edit?usp=sharing)

**Comment by jhonnycs** [comment]
pontos para modificar no TAP:

- [x] melhorar a descrição da demanda
- [x] adicionar a equipe nos stakeholders
