### ISSUE TITLE
Prototipos de baixa fidelidade

### ISSUE THREAD

**Issue by myller-silva** [myller-silva/gp-armarios-ifce#2]
## Objetivo:
Criar protótipos de baixa fidelidade para as principais telas do Sistema de Gerenciamento de Armários do IFCE, visando facilitar a visualização da interface e o fluxo de interação do usuário.

### Para Usuários (Alunos)

- [x] Tela de Login: Interface para autenticação dos alunos, permitindo acesso ao sistema.
- [x] Tela Principal (Dashboard): Visão geral dos armários disponíveis, opções de reserva e status dos armários.
- [x] Tela de Reserva de Armário: Formulário para seleção de armários, definição de datas de uso e confirmação da reserva.

### Para Administradores

- [x] Tela de Login do Administrador: Interface para autenticação dos administradores, permitindo acesso às funcionalidades administrativas.
- [x] Tela de Gerenciamento de Armários: Visão geral de todos os armários, incluindo opções para adicionar, editar e remover armários.
- [x] Tela de Relatórios: Interface para visualizar e exportar relatórios sobre o uso dos armários, incluindo reservas e ocupações.

## Critérios de Aceitação:

- [x] Protótipos finalizados e documentados.
- [x] Apresentação clara e compreensível para discussão em equipe.
- [x] Disponibilização dos protótipos no repositório para futuras referências.

**Comment by jhonnycs** [comment]
Acesse o protótipo [aqui](https://www.figma.com/design/SWzR5ILZv3vswk1e2IrWWi/arm%C3%A1rios-ifce?node-id=0-1&t=H41G8jYt7OvkD4GE-1)
